* Investment Proposal - Semiotic Limited
I'll be updating on this document over the next few weeks.
I'm currently the only shareholder.

Please see the following website for demonstrations of capabilities.

- https://semiosis.github.io/
- [[https://semiosis.github.io/posts/on-this-day-the-company-semiotic-was-started/][On this day, the company Semiotic was started]]

** Investment possibilities
Please contact myself or Anak to discuss options.
+ Shane :: [[mailto:mullikine@gmail.com]]
+ Anak :: [[mailto:awannaphasch2016@fau.edu]]

I'm interested in anywhere from small to
significant investment. Anything helps
currently. There is negligible development left to
do for the big debut, but I have big plans for the future.

*** $50,000
- Pay for essential hardware and AWS cloud services
*** $100,000
- Pay for essential hardware and AWS cloud services
*** $500,000
- Develop a standard web SAAS delivering the free-as-in-freedom Pen.el as a service, along with its source code
- Marketing
- Employ engineers to extend Pen.el with more language models
*** $1,000,000
- Develop a VSCode extension
- Develop a cryptocurrency
  - https://semiosis.github.io/protocol/

** Pricing model and ideas
- [[./pricing-model-and-product-ideas.org]]

** Positioning
Language models (LMs) are the new search engines
and databases of the next generation of the
internet, and in the last year, the number of
LM software as a service has grown from 3 (OpenAI's GPT-3, for example) to
about 20+ services (AI21, Cohere, for example).

On top of this, many smaller companies are
springing up to take advantage of LMs for a
new generation of internet applications. Take
conversion.ai, for example.

Semiotic (my startup) is positioning itself
right in the middle of that and has the first
language server that utilises these LMs to
provide human-intelligence augmenting functions
to VSCode, web browsers and other computing
interfaces.

It also has the first integrated prompting
server, and in the next month be deployed onto AWS to
provide both a language server and prompting
server for incorporation into AWS cloud
services.

The company will generate revenue from the
leasing of the docker container, and from
support services, but will have zero fees and
zero visibility on the prompts which are run.
It's a private and configurable server for
prompting.

Pen.el is Semiotic's flagship product. It can be tailored (with language model
fine-tuning) to each individual company's requirements, and as an example, can
provide documentation, chatbots and imaginary
languages, and other futuristic human-computer
interfaces for interacting intelligently within almost any
topic or context conceivable. It may, for instance be used to create
coersive or charming conversation, by
searching downstream LM generations, or
providing a chatbot for the things you are
currently looking at, physically (in real life) or virtually (in an AI generated world-wide-web).

Semiotic builds human intelligence-augmenting
products, and is aimed to be the backbone of
other startups and businesses that want to
utilisise GPT-3 or any other LM within their
own products and services, and to make it as
easy as possible, transparent and configurable
to do so.

*** Example use-cases
In layman's terms, if you were to be speaking
to somebody you like, it may search the
virtual multiverse for things you might say
which would result in evoking positive
responses and outcomes from that person, thus
enabling the development of an application
which services the user to present him or her
with conversational suggestions that are
charming.

In the same, way these types of
mechanisms can be used to augment the
productivity of programmers, as the LSP server
plugs directly into the developer's editor to
provide documentation and refactoring
functions, and lead the developer down avenues
of productivity. You might be perusing a
museum or art gallery and wish to talk to a
subject matter expert about what you are
currently experiencing, visually, audibly,
etc. and these inputs may be fed into world
models and LMs to provide a subject matter
expert for you to converse with.

These capabilities already exist in Pen.el, awaiting deployment to AWS and manages it
by utilising a combination of AlephAlpha's
world model, OpenAI's GPT-3 and other models.

** Expression of interest
If you would like to talk more about investing in Semiotic, please contact me at [[mailto:mullikine@gmail.com]].